const materialSystem = require('./materialSystem');

/**
 * Export Service - Generates 3D file format data
 * Supports OBJ, GLTF, and FBX formats
 */
class ExportService {
  /**
   * Export geometry to specified format
   */
  exportGeometry(geometryData, format, options = {}) {
    const normalizedFormat = format.toLowerCase();
    
    switch (normalizedFormat) {
      case 'obj':
        return this.exportToOBJ(geometryData, options);
      case 'gltf':
      case 'glb':
        return this.exportToGLTF(geometryData, options);
      case 'fbx':
        return this.exportToFBX(geometryData, options);
      default:
        throw new Error(`Unsupported format: ${format}`);
    }
  }

  /**
   * Export to OBJ format
   */
  exportToOBJ(geometryData, options = {}) {
    let objContent = '# Generated by ArchDisc\n';
    objContent += `# ${new Date().toISOString()}\n\n`;
    
    let mtlContent = '# Material Library\n\n';
    const materials = new Set();
    
    let vertexOffset = 1;
    let normalOffset = 1;
    
    const meshes = this.flattenGeometry(geometryData);
    
    meshes.forEach((mesh, meshIndex) => {
      const meshName = mesh.name || `mesh_${meshIndex}`;
      objContent += `\no ${meshName}\n`;
      
      // Generate vertices and normals
      const meshData = this.generateMeshData(mesh);
      
      // Write vertices
      meshData.vertices.forEach(v => {
        objContent += `v ${v.x.toFixed(6)} ${v.y.toFixed(6)} ${v.z.toFixed(6)}\n`;
      });
      
      // Write normals
      meshData.normals.forEach(n => {
        objContent += `vn ${n.x.toFixed(6)} ${n.y.toFixed(6)} ${n.z.toFixed(6)}\n`;
      });
      
      // Material
      const materialName = mesh.materialName || 'default';
      materials.add(materialName);
      objContent += `usemtl ${materialName}\n`;
      
      // Write faces
      meshData.faces.forEach(face => {
        const v1 = face[0] + vertexOffset;
        const v2 = face[1] + vertexOffset;
        const v3 = face[2] + vertexOffset;
        const n1 = face[0] + normalOffset;
        const n2 = face[1] + normalOffset;
        const n3 = face[2] + normalOffset;
        objContent += `f ${v1}//${n1} ${v2}//${n2} ${v3}//${n3}\n`;
      });
      
      vertexOffset += meshData.vertices.length;
      normalOffset += meshData.normals.length;
      objContent += '\n';
    });
    
    // Generate MTL file
    materials.forEach(matName => {
      const material = materialSystem.getMaterial(matName);
      mtlContent += `\nnewmtl ${matName}\n`;
      mtlContent += `Ka ${material.baseColor[0].toFixed(3)} ${material.baseColor[1].toFixed(3)} ${material.baseColor[2].toFixed(3)}\n`;
      mtlContent += `Kd ${material.baseColor[0].toFixed(3)} ${material.baseColor[1].toFixed(3)} ${material.baseColor[2].toFixed(3)}\n`;
      mtlContent += `Ks ${material.metallic.toFixed(3)} ${material.metallic.toFixed(3)} ${material.metallic.toFixed(3)}\n`;
      mtlContent += `Ns ${((1 - material.roughness) * 1000).toFixed(1)}\n`;
      mtlContent += `d ${material.transmission ? (1 - material.transmission).toFixed(3) : '1.000'}\n`;
      
      if (material.metallic > 0.5) {
        mtlContent += `illum 3\n`; // Reflection
      } else {
        mtlContent += `illum 2\n`; // Standard
      }
    });
    
    return {
      obj: objContent,
      mtl: mtlContent,
      filename: 'model.obj',
      mtlFilename: 'model.mtl',
    };
  }

  /**
   * Export to GLTF format
   */
  exportToGLTF(geometryData, options = {}) {
    const gltf = {
      asset: {
        version: '2.0',
        generator: 'ArchDisc',
      },
      scene: 0,
      scenes: [
        {
          nodes: [],
        },
      ],
      nodes: [],
      meshes: [],
      materials: [],
      accessors: [],
      bufferViews: [],
      buffers: [],
    };
    
    const meshes = this.flattenGeometry(geometryData);
    const materialsMap = new Map();
    
    meshes.forEach((mesh, meshIndex) => {
      const meshData = this.generateMeshData(mesh);
      
      // Create material if not exists
      const materialName = mesh.materialName || 'default';
      if (!materialsMap.has(materialName)) {
        const matIndex = gltf.materials.length;
        materialsMap.set(materialName, matIndex);
        gltf.materials.push(this.createGLTFMaterial(materialName));
      }
      
      // Create mesh
      const gltfMesh = {
        name: mesh.name || `mesh_${meshIndex}`,
        primitives: [
          {
            attributes: {
              POSITION: gltf.accessors.length,
              NORMAL: gltf.accessors.length + 1,
            },
            indices: gltf.accessors.length + 2,
            material: materialsMap.get(materialName),
          },
        ],
      };
      
      // Add accessors for positions, normals, and indices
      // (Simplified - in real implementation, would include actual buffer data)
      gltf.accessors.push(
        {
          bufferView: 0,
          componentType: 5126, // FLOAT
          count: meshData.vertices.length,
          type: 'VEC3',
          min: this.calculateMin(meshData.vertices),
          max: this.calculateMax(meshData.vertices),
        },
        {
          bufferView: 1,
          componentType: 5126, // FLOAT
          count: meshData.normals.length,
          type: 'VEC3',
        },
        {
          bufferView: 2,
          componentType: 5123, // UNSIGNED_SHORT
          count: meshData.faces.length * 3,
          type: 'SCALAR',
        }
      );
      
      gltf.meshes.push(gltfMesh);
      
      // Create node
      const node = {
        name: mesh.name || `node_${meshIndex}`,
        mesh: gltf.meshes.length - 1,
      };
      
      if (mesh.position) {
        node.translation = [mesh.position.x, mesh.position.y, mesh.position.z];
      }
      
      gltf.nodes.push(node);
      gltf.scenes[0].nodes.push(gltf.nodes.length - 1);
    });
    
    return {
      gltf: JSON.stringify(gltf, null, 2),
      filename: 'model.gltf',
      format: 'gltf',
    };
  }

  /**
   * Export to FBX format (data structure)
   */
  exportToFBX(geometryData, options = {}) {
    // FBX is a complex binary format, so we'll create a JSON representation
    // that describes the FBX structure
    const fbxData = {
      format: 'FBX',
      version: '7.4',
      creator: 'ArchDisc',
      creationTime: new Date().toISOString(),
      objects: [],
      connections: [],
      materials: [],
    };
    
    const meshes = this.flattenGeometry(geometryData);
    
    meshes.forEach((mesh, meshIndex) => {
      const meshData = this.generateMeshData(mesh);
      
      // Add mesh object
      fbxData.objects.push({
        type: 'Geometry',
        id: 1000000 + meshIndex,
        name: mesh.name || `mesh_${meshIndex}`,
        vertices: meshData.vertices,
        normals: meshData.normals,
        faces: meshData.faces,
        uvs: [], // Placeholder for UV coordinates
      });
      
      // Add model object
      fbxData.objects.push({
        type: 'Model',
        id: 2000000 + meshIndex,
        name: mesh.name || `model_${meshIndex}`,
        translation: mesh.position || { x: 0, y: 0, z: 0 },
        rotation: mesh.rotation || { x: 0, y: 0, z: 0 },
        scale: mesh.scale || { x: 1, y: 1, z: 1 },
      });
      
      // Add material
      const materialName = mesh.materialName || 'default';
      const material = materialSystem.getMaterial(materialName);
      fbxData.materials.push({
        id: 3000000 + meshIndex,
        name: materialName,
        properties: {
          diffuse: material.baseColor,
          specular: material.metallic > 0.5 ? [1, 1, 1] : [0.2, 0.2, 0.2],
          shininess: (1 - material.roughness) * 100,
          opacity: material.transmission ? 1 - material.transmission : 1,
        },
      });
      
      // Add connections
      fbxData.connections.push(
        {
          type: 'OO',
          from: 1000000 + meshIndex,
          to: 2000000 + meshIndex,
        },
        {
          type: 'OO',
          from: 3000000 + meshIndex,
          to: 2000000 + meshIndex,
        }
      );
    });
    
    return {
      fbx: JSON.stringify(fbxData, null, 2),
      filename: 'model.fbx.json',
      format: 'fbx',
      note: 'This is a JSON representation of FBX structure',
    };
  }

  /**
   * Flatten geometry hierarchy into list of meshes
   */
  flattenGeometry(geometryData) {
    const meshes = [];
    
    if (geometryData.type === 'scene') {
      // Handle scene with multiple meshes
      if (geometryData.meshes) {
        meshes.push(...geometryData.meshes);
      }
      
      // Handle instanced objects
      if (geometryData.instances) {
        geometryData.instances.forEach(instance => {
          instance.positions.forEach((pos, idx) => {
            meshes.push({
              ...instance.mesh,
              position: pos,
              name: `${instance.mesh.name || 'instance'}_${idx}`,
            });
          });
        });
      }
    } else if (geometryData.type === 'object') {
      // Handle single object
      meshes.push(geometryData.mesh);
    } else if (geometryData.type === 'composite') {
      // Handle composite geometry
      return [geometryData];
    }
    
    return meshes;
  }

  /**
   * Generate mesh data (vertices, normals, faces) from geometry definition
   */
  generateMeshData(mesh) {
    if (mesh.type === 'composite' && mesh.parts) {
      // Combine all parts
      const allVertices = [];
      const allNormals = [];
      const allFaces = [];
      let vertexOffset = 0;
      
      mesh.parts.forEach(part => {
        const partData = this.generateMeshDataForPrimitive(part);
        
        allVertices.push(...partData.vertices);
        allNormals.push(...partData.normals);
        
        partData.faces.forEach(face => {
          allFaces.push([
            face[0] + vertexOffset,
            face[1] + vertexOffset,
            face[2] + vertexOffset,
          ]);
        });
        
        vertexOffset += partData.vertices.length;
      });
      
      return { vertices: allVertices, normals: allNormals, faces: allFaces };
    } else {
      return this.generateMeshDataForPrimitive(mesh);
    }
  }

  /**
   * Generate mesh data for primitive shapes
   */
  generateMeshDataForPrimitive(primitive) {
    const type = primitive.type?.toLowerCase() || 'box';
    
    switch (type) {
      case 'box':
        return this.generateBoxMesh(primitive);
      case 'sphere':
        return this.generateSphereMesh(primitive);
      case 'cylinder':
        return this.generateCylinderMesh(primitive);
      case 'plane':
        return this.generatePlaneMesh(primitive);
      default:
        return this.generateBoxMesh(primitive);
    }
  }

  /**
   * Generate box mesh
   */
  generateBoxMesh(box) {
    const dim = box.dimensions || { x: 1, y: 1, z: 1 };
    const pos = box.position || { x: 0, y: 0, z: 0 };
    const w = dim.x / 2, h = dim.y / 2, d = dim.z / 2;
    
    const vertices = [
      // Front face
      { x: pos.x - w, y: pos.y - h, z: pos.z + d },
      { x: pos.x + w, y: pos.y - h, z: pos.z + d },
      { x: pos.x + w, y: pos.y + h, z: pos.z + d },
      { x: pos.x - w, y: pos.y + h, z: pos.z + d },
      // Back face
      { x: pos.x - w, y: pos.y - h, z: pos.z - d },
      { x: pos.x - w, y: pos.y + h, z: pos.z - d },
      { x: pos.x + w, y: pos.y + h, z: pos.z - d },
      { x: pos.x + w, y: pos.y - h, z: pos.z - d },
      // Top face
      { x: pos.x - w, y: pos.y + h, z: pos.z - d },
      { x: pos.x - w, y: pos.y + h, z: pos.z + d },
      { x: pos.x + w, y: pos.y + h, z: pos.z + d },
      { x: pos.x + w, y: pos.y + h, z: pos.z - d },
      // Bottom face
      { x: pos.x - w, y: pos.y - h, z: pos.z - d },
      { x: pos.x + w, y: pos.y - h, z: pos.z - d },
      { x: pos.x + w, y: pos.y - h, z: pos.z + d },
      { x: pos.x - w, y: pos.y - h, z: pos.z + d },
      // Right face
      { x: pos.x + w, y: pos.y - h, z: pos.z - d },
      { x: pos.x + w, y: pos.y + h, z: pos.z - d },
      { x: pos.x + w, y: pos.y + h, z: pos.z + d },
      { x: pos.x + w, y: pos.y - h, z: pos.z + d },
      // Left face
      { x: pos.x - w, y: pos.y - h, z: pos.z - d },
      { x: pos.x - w, y: pos.y - h, z: pos.z + d },
      { x: pos.x - w, y: pos.y + h, z: pos.z + d },
      { x: pos.x - w, y: pos.y + h, z: pos.z - d },
    ];
    
    const normals = [
      // Front
      { x: 0, y: 0, z: 1 }, { x: 0, y: 0, z: 1 }, { x: 0, y: 0, z: 1 }, { x: 0, y: 0, z: 1 },
      // Back
      { x: 0, y: 0, z: -1 }, { x: 0, y: 0, z: -1 }, { x: 0, y: 0, z: -1 }, { x: 0, y: 0, z: -1 },
      // Top
      { x: 0, y: 1, z: 0 }, { x: 0, y: 1, z: 0 }, { x: 0, y: 1, z: 0 }, { x: 0, y: 1, z: 0 },
      // Bottom
      { x: 0, y: -1, z: 0 }, { x: 0, y: -1, z: 0 }, { x: 0, y: -1, z: 0 }, { x: 0, y: -1, z: 0 },
      // Right
      { x: 1, y: 0, z: 0 }, { x: 1, y: 0, z: 0 }, { x: 1, y: 0, z: 0 }, { x: 1, y: 0, z: 0 },
      // Left
      { x: -1, y: 0, z: 0 }, { x: -1, y: 0, z: 0 }, { x: -1, y: 0, z: 0 }, { x: -1, y: 0, z: 0 },
    ];
    
    const faces = [];
    for (let i = 0; i < 6; i++) {
      const offset = i * 4;
      faces.push([offset, offset + 1, offset + 2]);
      faces.push([offset, offset + 2, offset + 3]);
    }
    
    return { vertices, normals, faces };
  }

  /**
   * Generate sphere mesh
   */
  generateSphereMesh(sphere) {
    const radius = sphere.radius || 1;
    const pos = sphere.position || { x: 0, y: 0, z: 0 };
    const segments = 16;
    const rings = 12;
    
    const vertices = [];
    const normals = [];
    const faces = [];
    
    for (let ring = 0; ring <= rings; ring++) {
      const phi = (ring / rings) * Math.PI;
      const sinPhi = Math.sin(phi);
      const cosPhi = Math.cos(phi);
      
      for (let seg = 0; seg <= segments; seg++) {
        const theta = (seg / segments) * Math.PI * 2;
        const sinTheta = Math.sin(theta);
        const cosTheta = Math.cos(theta);
        
        const x = cosTheta * sinPhi;
        const y = cosPhi;
        const z = sinTheta * sinPhi;
        
        vertices.push({
          x: pos.x + radius * x,
          y: pos.y + radius * y,
          z: pos.z + radius * z,
        });
        
        normals.push({ x, y, z });
      }
    }
    
    for (let ring = 0; ring < rings; ring++) {
      for (let seg = 0; seg < segments; seg++) {
        const first = ring * (segments + 1) + seg;
        const second = first + segments + 1;
        
        faces.push([first, second, first + 1]);
        faces.push([second, second + 1, first + 1]);
      }
    }
    
    return { vertices, normals, faces };
  }

  /**
   * Generate cylinder mesh
   */
  generateCylinderMesh(cylinder) {
    const radius = cylinder.radius || 1;
    const height = cylinder.height || 2;
    const pos = cylinder.position || { x: 0, y: 0, z: 0 };
    const segments = 16;
    
    const vertices = [];
    const normals = [];
    const faces = [];
    
    // Generate vertices
    for (let i = 0; i <= segments; i++) {
      const theta = (i / segments) * Math.PI * 2;
      const x = Math.cos(theta);
      const z = Math.sin(theta);
      
      // Top circle
      vertices.push({
        x: pos.x + radius * x,
        y: pos.y + height / 2,
        z: pos.z + radius * z,
      });
      normals.push({ x, y: 0, z });
      
      // Bottom circle
      vertices.push({
        x: pos.x + radius * x,
        y: pos.y - height / 2,
        z: pos.z + radius * z,
      });
      normals.push({ x, y: 0, z });
    }
    
    // Generate faces for sides
    for (let i = 0; i < segments; i++) {
      const a = i * 2;
      const b = a + 1;
      const c = ((i + 1) % segments) * 2;
      const d = c + 1;
      
      faces.push([a, b, c]);
      faces.push([b, d, c]);
    }
    
    return { vertices, normals, faces };
  }

  /**
   * Generate plane mesh
   */
  generatePlaneMesh(plane) {
    const dim = plane.dimensions || { x: 10, z: 10 };
    const pos = plane.position || { x: 0, y: 0, z: 0 };
    const subdivisions = plane.subdivisions || 1;
    
    const vertices = [];
    const normals = [];
    const faces = [];
    
    for (let i = 0; i <= subdivisions; i++) {
      for (let j = 0; j <= subdivisions; j++) {
        const x = pos.x + (i / subdivisions - 0.5) * dim.x;
        const z = pos.z + (j / subdivisions - 0.5) * dim.z;
        
        vertices.push({ x, y: pos.y, z });
        normals.push({ x: 0, y: 1, z: 0 });
      }
    }
    
    for (let i = 0; i < subdivisions; i++) {
      for (let j = 0; j < subdivisions; j++) {
        const a = i * (subdivisions + 1) + j;
        const b = a + 1;
        const c = a + subdivisions + 1;
        const d = c + 1;
        
        faces.push([a, c, b]);
        faces.push([b, c, d]);
      }
    }
    
    return { vertices, normals, faces };
  }

  /**
   * Create GLTF material
   */
  createGLTFMaterial(materialName) {
    const material = materialSystem.getMaterial(materialName);
    
    return {
      name: material.name,
      pbrMetallicRoughness: {
        baseColorFactor: [...material.baseColor, 1.0],
        metallicFactor: material.metallic,
        roughnessFactor: material.roughness,
      },
      doubleSided: true,
    };
  }

  /**
   * Calculate min bounds for vertices
   */
  calculateMin(vertices) {
    if (vertices.length === 0) return [0, 0, 0];
    
    let minX = Infinity, minY = Infinity, minZ = Infinity;
    vertices.forEach(v => {
      minX = Math.min(minX, v.x);
      minY = Math.min(minY, v.y);
      minZ = Math.min(minZ, v.z);
    });
    
    return [minX, minY, minZ];
  }

  /**
   * Calculate max bounds for vertices
   */
  calculateMax(vertices) {
    if (vertices.length === 0) return [0, 0, 0];
    
    let maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;
    vertices.forEach(v => {
      maxX = Math.max(maxX, v.x);
      maxY = Math.max(maxY, v.y);
      maxZ = Math.max(maxZ, v.z);
    });
    
    return [maxX, maxY, maxZ];
  }
}

module.exports = new ExportService();
