/**
 * Routing workbench — cable / pipe / hose path-along-curve with bend-radius
 * enforcement.
 *
 * Data model only; the actual 3D pipe geometry is generated by sweeping a
 * circular profile along the path through forge.cam.sweep / the native
 * sweep op (queued for Forge-15b). For now we model the topology + the
 * bend-radius check that flags any spline span tighter than the minimum
 * allowed by the harness / pipe spec.
 */

let nextId = 1;
function uid(p) { return `${p}-${nextId++}`; }

export const RouteKind = Object.freeze({
  Cable: 'cable',
  Pipe:  'pipe',
  Hose:  'hose',
});

export class RoutePoint {
  constructor({ position, fixed = false, tangent = null, name = null }) {
    if (!position || position.length !== 3) {
      throw new Error('[forge.route] position must be [x,y,z]');
    }
    this.id = uid('rp');
    this.position = [...position];
    this.fixed = fixed;           // if true, solver pins this node
    this.tangent = tangent ? [...tangent] : null;
    this.name = name || this.id;
  }
}

export class Route {
  constructor({ kind = RouteKind.Pipe, diameter, minBendRadius, material = null, name = null } = {}) {
    if (!diameter) throw new Error('[forge.route] diameter is required (mm)');
    if (!minBendRadius) throw new Error('[forge.route] minBendRadius is required (mm)');
    this.id = uid('route');
    this.kind = kind;
    this.diameter = diameter;
    this.minBendRadius = minBendRadius;
    this.material = material;
    this.name = name || `${kind}-${this.id}`;
    this.points = [];             // RoutePoint[]
    this.violations = [];         // populated by checkBendRadius()
  }
  addPoint(spec) {
    const p = spec instanceof RoutePoint ? spec : new RoutePoint(spec);
    this.points.push(p);
    return p;
  }
  /**
   * Estimate the radius of curvature at each interior point using the
   * three-point circle through (p_{i-1}, p_i, p_{i+1}) and flag any that
   * fall under `minBendRadius`. Returns the violation list.
   */
  checkBendRadius() {
    this.violations = [];
    for (let i = 1; i < this.points.length - 1; i++) {
      const a = this.points[i - 1].position;
      const b = this.points[i].position;
      const c = this.points[i + 1].position;
      const r = circumradius3(a, b, c);
      if (r !== null && r < this.minBendRadius) {
        this.violations.push({
          pointId: this.points[i].id,
          actualRadius: r,
          allowed: this.minBendRadius,
        });
      }
    }
    return this.violations;
  }
  /** Total path length, polyline sum. */
  length() {
    let L = 0;
    for (let i = 1; i < this.points.length; i++) {
      const a = this.points[i - 1].position;
      const b = this.points[i].position;
      L += Math.hypot(b[0] - a[0], b[1] - a[1], b[2] - a[2]);
    }
    return L;
  }
}

/** 3-point circumradius. Returns null on collinear / degenerate input. */
function circumradius3(a, b, c) {
  const abx = b[0] - a[0], aby = b[1] - a[1], abz = b[2] - a[2];
  const acx = c[0] - a[0], acy = c[1] - a[1], acz = c[2] - a[2];
  // cross(ab, ac)
  const nx = aby * acz - abz * acy;
  const ny = abz * acx - abx * acz;
  const nz = abx * acy - aby * acx;
  const cross = Math.hypot(nx, ny, nz);
  if (cross < 1e-12) return null;
  const abLen = Math.hypot(abx, aby, abz);
  const acLen = Math.hypot(acx, acy, acz);
  const bcLen = Math.hypot(c[0] - b[0], c[1] - b[1], c[2] - b[2]);
  return (abLen * acLen * bcLen) / (2 * cross);
}
