// Forge-152 — Robot post-processors.
//
// Emit OEM-native robot programs from a waypoint list:
//
//   KUKA  → KRL   (.src file body)        — KUKA Robot Language
//   ABB   → RAPID (.mod file body)        — ABB IRC5 RAPID
//   FANUC → TP    (.ls   teach-pendant)   — FANUC LR Mate dialect
//
// Each post takes the same waypoint shape so the UI doesn't have to
// know about syntax:
//
//   waypoint = {
//     name?:     string                  // optional display label
//     moveType:  'PTP' | 'LIN' | 'CIRC'  // joint / linear / circular
//     joints:    [J1, J2, J3, J4, J5, J6]  in DEGREES
//     pose:      [x, y, z, A, B, C]       mm + ZYX Euler degrees
//     viaPose?:  [x, y, z, A, B, C]       only for CIRC
//     speed:     number                   mm/s for LIN/CIRC, %ofMax for PTP
//     accel?:    number                   m/s²    (mapped per OEM)
//     blendRadius?: number                mm      (CNT / C_DIS / fine)
//     tool?:     string                   tool data name
//     base?:     string                   base/work-object name
//     load?:     number                   tool mass in kg
//   }
//
// PROGRAM HEADER pulls metadata from { robotId, programName,
// author, tool, base, load } passed in `meta`.
//
// All three syntaxes follow the OEM reference manuals — KUKA
// "KSS Operating and Programming Instructions for System Integrators",
// ABB "RAPID Reference Manual — Instructions", FANUC "R-30iA / R-30iB
// HandlingTool Operator's Manual".

import { getRobotModel } from './robotModels.js';

// ────────────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────────────

function fmt(n, digits = 3) {
  if (typeof n !== 'number' || !isFinite(n)) return '0.000';
  return n.toFixed(digits);
}

function sanitizeName(s, max = 24) {
  // Robot identifiers: A-Z, 0-9, underscore, must start with a letter.
  const cleaned = String(s ?? 'PROG')
    .toUpperCase()
    .replace(/[^A-Z0-9_]/g, '_')
    .replace(/^[^A-Z]+/, 'P_');
  return cleaned.slice(0, max);
}

function nowIsoLocal() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

// ────────────────────────────────────────────────────────────────────
// KUKA KRL  — *.src
// ────────────────────────────────────────────────────────────────────
//
//   DEF MyProg()
//     INI
//     $TOOL = TOOL_DATA[1]
//     $BASE = BASE_DATA[1]
//     $LOAD = LOAD_DATA[1]
//     PTP {A1 0, A2 -90, A3 90, A4 0, A5 0, A6 0} C_PTP
//     LIN {X 500, Y 0, Z 600, A 0, B 0, C 180} C_DIS
//     CIRC { …via… }, { …target… } C_DIS
//   END

export function postKRL(meta, waypoints) {
  const robot = getRobotModel(meta.robotId);
  const progName = sanitizeName(meta.programName || 'FORGE_PROG');
  const lines = [];
  lines.push(`; ${'='.repeat(58)}`);
  lines.push(`; KUKA KRL program — generated by ArchDisc Forge v4`);
  lines.push(`; Robot   : ${robot ? robot.name : meta.robotId}`);
  lines.push(`; Author  : ${meta.author || 'forge-user'}`);
  lines.push(`; Created : ${nowIsoLocal()}`);
  lines.push(`; Waypoints: ${waypoints.length}`);
  lines.push(`; ${'='.repeat(58)}`);
  lines.push(`DEF ${progName}()`);
  lines.push(`  INI`);
  lines.push(`  ; ---------------- tool / base / load ----------------`);
  lines.push(`  $TOOL = TOOL_DATA[${(meta.toolId ?? 1)}]`);
  lines.push(`  $BASE = BASE_DATA[${(meta.baseId ?? 1)}]`);
  lines.push(`  $LOAD = LOAD_DATA[${(meta.loadId ?? 1)}]`);
  // Reasonable default override speeds. KUKA $VEL.CP is m/s here.
  lines.push(`  $VEL.CP = 2.000`);
  lines.push(`  $ACC.CP = 2.0`);
  lines.push(`  $APO.CDIS = 5.0`);
  lines.push(`  ; ---------------- motion --------------------------`);

  for (let i = 0; i < waypoints.length; i++) {
    const w = waypoints[i];
    const tag = w.name ? `; -- ${w.name}` : `; -- WP${i+1}`;
    lines.push(`  ${tag}`);
    if (w.speed != null) {
      if (w.moveType === 'PTP') {
        lines.push(`  $VEL_AXIS[1] = ${fmt(w.speed, 1)}`);
      } else {
        lines.push(`  $VEL.CP = ${fmt(w.speed / 1000, 3)}`);    // mm/s → m/s
      }
    }
    if (w.blendRadius != null) {
      lines.push(`  $APO.CDIS = ${fmt(w.blendRadius, 1)}`);
    }
    const apoTag = (w.blendRadius != null && w.blendRadius > 0) ? ' C_DIS' : '';
    if (w.moveType === 'PTP') {
      const j = w.joints || [0,0,0,0,0,0];
      lines.push(`  PTP {A1 ${fmt(j[0])}, A2 ${fmt(j[1])}, A3 ${fmt(j[2])}, A4 ${fmt(j[3])}, A5 ${fmt(j[4])}, A6 ${fmt(j[5])}}${apoTag}`);
    } else if (w.moveType === 'LIN') {
      const p = w.pose;
      lines.push(`  LIN {X ${fmt(p[0])}, Y ${fmt(p[1])}, Z ${fmt(p[2])}, A ${fmt(p[3])}, B ${fmt(p[4])}, C ${fmt(p[5])}}${apoTag}`);
    } else if (w.moveType === 'CIRC') {
      const v = w.viaPose || w.pose;
      const p = w.pose;
      lines.push(`  CIRC {X ${fmt(v[0])}, Y ${fmt(v[1])}, Z ${fmt(v[2])}, A ${fmt(v[3])}, B ${fmt(v[4])}, C ${fmt(v[5])}}, {X ${fmt(p[0])}, Y ${fmt(p[1])}, Z ${fmt(p[2])}, A ${fmt(p[3])}, B ${fmt(p[4])}, C ${fmt(p[5])}}${apoTag}`);
    } else {
      lines.push(`  ; (unknown move type: ${w.moveType})`);
    }
  }

  lines.push(`END`);
  return lines.join('\n') + '\n';
}

// ────────────────────────────────────────────────────────────────────
// ABB RAPID  — *.mod
// ────────────────────────────────────────────────────────────────────
//
//   MODULE MyProg
//     PERS tooldata tGripper := [ ... ];
//     PERS wobjdata wPart    := [ ... ];
//     PERS loaddata lGripper := [ ... ];
//     CONST jointtarget jHome := [[0,0,0,0,0,0],[9E9,...]];
//     CONST robtarget   pP1   := [[500,0,600],[0,0,1,0],[...],[9E9,...]];
//
//     PROC main()
//       MoveAbsJ jHome\NoEOffs, v1000, fine, tGripper\WObj:=wPart;
//       MoveL    pP1, v500, z10, tGripper\WObj:=wPart;
//       MoveC    pVia, pP1, v500, z10, tGripper\WObj:=wPart;
//     ENDPROC
//   ENDMODULE
//
// Quaternion conversion: ABB uses [q1, q2, q3, q4] = [w, x, y, z].

function eulerZYXToQuaternionWxyz([ADeg, BDeg, CDeg]) {
  const A = ADeg * Math.PI / 180;
  const B = BDeg * Math.PI / 180;
  const C = CDeg * Math.PI / 180;
  // ZYX intrinsic (RAPID's "natural" representation).
  const cA = Math.cos(A/2), sA = Math.sin(A/2);
  const cB = Math.cos(B/2), sB = Math.sin(B/2);
  const cC = Math.cos(C/2), sC = Math.sin(C/2);
  const w = cA*cB*cC + sA*sB*sC;
  const x = cA*cB*sC - sA*sB*cC;
  const y = cA*sB*cC + sA*cB*sC;
  const z = sA*cB*cC - cA*sB*sC;
  return [w, x, y, z];
}

function abbSpeedTag(mmps) {
  // RAPID uses v100, v500, v1000 named constants. We always emit
  // explicit speeddata so callers get exactly what they asked for.
  return `[${fmt(mmps, 1)}, 500, 5000, 1000]`;
}
function abbZoneTag(blend_mm) {
  if (blend_mm == null || blend_mm <= 0) return 'fine';
  // RAPID's zonedata is [finep, pzone_tcp, pzone_ori, pzone_eax,
  // zone_ori, zone_leax, zone_reax].
  return `[FALSE, ${fmt(blend_mm,1)}, ${fmt(blend_mm*1.5,1)}, ${fmt(blend_mm*1.5,1)}, ${fmt(blend_mm/10,1)}, ${fmt(blend_mm/10,1)}, ${fmt(blend_mm/10,1)}]`;
}

export function postRAPID(meta, waypoints) {
  const robot = getRobotModel(meta.robotId);
  const progName = sanitizeName(meta.programName || 'FORGE_PROG');
  const toolName = sanitizeName(meta.toolName || 'TGRIPPER');
  const wobjName = sanitizeName(meta.baseName || 'WPART');
  const lines = [];
  lines.push(`MODULE ${progName}`);
  lines.push(`  ! ===========================================================`);
  lines.push(`  ! ABB RAPID program — generated by ArchDisc Forge v4`);
  lines.push(`  ! Robot   : ${robot ? robot.name : meta.robotId}`);
  lines.push(`  ! Author  : ${meta.author || 'forge-user'}`);
  lines.push(`  ! Created : ${nowIsoLocal()}`);
  lines.push(`  ! Waypoints: ${waypoints.length}`);
  lines.push(`  ! ===========================================================`);

  // Tool / wobj / load PERS records.
  const loadKg = meta.load ?? 1.0;
  lines.push(`  PERS tooldata ${toolName} := [TRUE, [[0,0,150],[1,0,0,0]], [${fmt(loadKg,2)}, [0,0,80], [1,0,0,0], 0, 0, 0]];`);
  lines.push(`  PERS wobjdata ${wobjName} := [FALSE, TRUE, "", [[0,0,0],[1,0,0,0]], [[0,0,0],[1,0,0,0]]];`);
  lines.push(``);

  // Build typed targets.
  const usedJointTargets = [];
  const usedRobTargets   = [];
  for (let i = 0; i < waypoints.length; i++) {
    const w = waypoints[i];
    const label = w.name ? sanitizeName(w.name, 18) : `P${i+1}`;
    if (w.moveType === 'PTP') {
      const j = w.joints || [0,0,0,0,0,0];
      lines.push(`  CONST jointtarget j${label} := [[${j.map((x) => fmt(x)).join(', ')}], [9E9,9E9,9E9,9E9,9E9,9E9]];`);
      usedJointTargets.push({ label, w });
    } else {
      const p = w.pose;
      const q = eulerZYXToQuaternionWxyz([p[3], p[4], p[5]]);
      lines.push(`  CONST robtarget p${label} := [[${fmt(p[0])}, ${fmt(p[1])}, ${fmt(p[2])}], [${q.map((x) => fmt(x,6)).join(', ')}], [0,0,0,0], [9E9,9E9,9E9,9E9,9E9,9E9]];`);
      if (w.moveType === 'CIRC' && w.viaPose) {
        const v = w.viaPose;
        const qv = eulerZYXToQuaternionWxyz([v[3], v[4], v[5]]);
        lines.push(`  CONST robtarget p${label}_via := [[${fmt(v[0])}, ${fmt(v[1])}, ${fmt(v[2])}], [${qv.map((x) => fmt(x,6)).join(', ')}], [0,0,0,0], [9E9,9E9,9E9,9E9,9E9,9E9]];`);
      }
      usedRobTargets.push({ label, w });
    }
  }

  lines.push(``);
  lines.push(`  PROC main()`);
  for (let i = 0; i < waypoints.length; i++) {
    const w = waypoints[i];
    const label = w.name ? sanitizeName(w.name, 18) : `P${i+1}`;
    const vel  = abbSpeedTag(w.speed ?? 250);
    const zone = abbZoneTag(w.blendRadius);
    if (w.moveType === 'PTP') {
      lines.push(`    MoveAbsJ j${label}\\NoEOffs, ${vel}, ${zone}, ${toolName}\\WObj:=${wobjName};`);
    } else if (w.moveType === 'LIN') {
      lines.push(`    MoveL p${label}, ${vel}, ${zone}, ${toolName}\\WObj:=${wobjName};`);
    } else if (w.moveType === 'CIRC') {
      const viaName = w.viaPose ? `p${label}_via` : `p${label}`;
      lines.push(`    MoveC ${viaName}, p${label}, ${vel}, ${zone}, ${toolName}\\WObj:=${wobjName};`);
    } else {
      lines.push(`    ! (unknown move type: ${w.moveType})`);
    }
  }
  lines.push(`  ENDPROC`);
  lines.push(`ENDMODULE`);
  return lines.join('\n') + '\n';
}

// ────────────────────────────────────────────────────────────────────
// FANUC TP — *.ls (ASCII teach-pendant listing)
// ────────────────────────────────────────────────────────────────────
//
//   /PROG  MYPROG
//   /ATTR
//   OWNER         = MNEDITOR;
//   COMMENT       = "Forge v4";
//   PROG_SIZE     = 0;
//   /MN
//      1:  UTOOL_NUM=1 ;
//      2:  UFRAME_NUM=1 ;
//      3:  PAYLOAD[1] ;
//      4:J P[1] 100% FINE    ;
//      5:L P[2] 500mm/sec CNT5 ;
//      6:C P[3]
//        : P[4] 500mm/sec CNT5 ;
//   /POS
//   P[1]{
//      GP1:
//        UF : 1, UT : 1,
//        J1=    0.000 deg, J2=    0.000 deg, ...
//   };
//   /END

function fanucPositionBlock(idx, w) {
  const out = [];
  out.push(`P[${idx}]{`);
  out.push(`   GP1:`);
  out.push(`      UF : 1, UT : 1,`);
  if (w.moveType === 'PTP' && w.joints) {
    const j = w.joints;
    out.push(`      J1=  ${fmt(j[0])} deg, J2=  ${fmt(j[1])} deg, J3=  ${fmt(j[2])} deg,`);
    out.push(`      J4=  ${fmt(j[3])} deg, J5=  ${fmt(j[4])} deg, J6=  ${fmt(j[5])} deg`);
  } else {
    const p = w.pose || [0,0,0,0,0,0];
    out.push(`      CONFIG : 'N U T, 0, 0, 0',`);
    out.push(`      X =  ${fmt(p[0])}  mm, Y =  ${fmt(p[1])}  mm, Z =  ${fmt(p[2])}  mm,`);
    out.push(`      W =  ${fmt(p[5])} deg, P =  ${fmt(p[4])} deg, R =  ${fmt(p[3])} deg`);
  }
  out.push(`};`);
  return out;
}

export function postTP(meta, waypoints) {
  const robot = getRobotModel(meta.robotId);
  const progName = sanitizeName(meta.programName || 'FORGE_PROG');
  const lines = [];
  lines.push(`/PROG  ${progName}`);
  lines.push(`/ATTR`);
  lines.push(`OWNER          = MNEDITOR;`);
  lines.push(`COMMENT        = "Forge v4 ${robot ? robot.name : meta.robotId}";`);
  lines.push(`PROG_SIZE      = 0;`);
  lines.push(`CREATE         = DATE ${nowIsoLocal()};`);
  lines.push(`MODIFIED       = DATE ${nowIsoLocal()};`);
  lines.push(`FILE_NAME      = ${progName};`);
  lines.push(`VERSION        = 0;`);
  lines.push(`LINE_COUNT     = ${waypoints.length + 3};`);
  lines.push(`MEMORY_SIZE    = 0;`);
  lines.push(`PROTECT        = READ_WRITE;`);
  lines.push(`TCD:  STACK_SIZE        = 0,`);
  lines.push(`      TASK_PRIORITY     = 50,`);
  lines.push(`      TIME_SLICE        = 0,`);
  lines.push(`      BUSY_LAMP_OFF     = 0,`);
  lines.push(`      ABORT_REQUEST     = 0,`);
  lines.push(`      PAUSE_REQUEST     = 0;`);
  lines.push(`DEFAULT_GROUP  = 1,*,*,*,*;`);
  lines.push(`CONTROL_CODE   = 00000000 00000000;`);
  lines.push(`/MN`);

  let lineNo = 0;
  const writeLine = (txt) => {
    lineNo += 1;
    lines.push(`   ${String(lineNo).padStart(2, ' ')}:${txt} ;`);
  };
  writeLine(`  UTOOL_NUM=${meta.toolId ?? 1}`);
  writeLine(`  UFRAME_NUM=${meta.baseId ?? 1}`);
  writeLine(`  PAYLOAD[${meta.loadId ?? 1}]`);

  for (let i = 0; i < waypoints.length; i++) {
    const w = waypoints[i];
    const idx = i + 1;
    const speed = (w.speed != null) ? w.speed : 500;
    const term  = (w.blendRadius != null && w.blendRadius > 0)
      ? `CNT${Math.max(0, Math.min(100, Math.round(w.blendRadius)))}`
      : 'FINE';
    if (w.moveType === 'PTP') {
      writeLine(`J P[${idx}] ${Math.round(Math.min(100, speed))}% ${term}`);
    } else if (w.moveType === 'LIN') {
      writeLine(`L P[${idx}] ${Math.round(speed)}mm/sec ${term}`);
    } else if (w.moveType === 'CIRC') {
      // CIRC needs a via point — emit two consecutive P[] references.
      // FANUC syntax: `C P[via] P[end] speed term`.
      lineNo += 1;
      lines.push(`   ${String(lineNo).padStart(2, ' ')}:C P[${idx}]`);
      lineNo += 1;
      lines.push(`     : P[${idx}_via] ${Math.round(speed)}mm/sec ${term} ;`);
    } else {
      writeLine(`! unknown move type: ${w.moveType}`);
    }
  }
  lines.push(`/POS`);
  for (let i = 0; i < waypoints.length; i++) {
    lines.push(...fanucPositionBlock(i + 1, waypoints[i]));
  }
  lines.push(`/END`);
  return lines.join('\n') + '\n';
}

// ────────────────────────────────────────────────────────────────────
// Public dispatch
// ────────────────────────────────────────────────────────────────────

export function postProcess(format, meta, waypoints) {
  switch (format) {
    case 'KRL':   return postKRL(meta, waypoints);
    case 'RAPID': return postRAPID(meta, waypoints);
    case 'TP':    return postTP(meta, waypoints);
    default: throw new Error(`Unknown robot post format: ${format}`);
  }
}

export function postExtensionFor(format) {
  switch (format) {
    case 'KRL':   return 'src';
    case 'RAPID': return 'mod';
    case 'TP':    return 'ls';
    default:      return 'txt';
  }
}

export default { postProcess, postKRL, postRAPID, postTP, postExtensionFor };
