/**
 * ArchDisc — HTML Report Builder
 *
 * Generates a self-contained interactive HTML report that summarizes a
 * project: components, tests, analyses, validation results, screenshots,
 * BOM. Opens in any browser; no server required. Embeds images as base64
 * if provided, otherwise references them by relative path.
 *
 * Used as the primary "deliverable" for any project — schools, engineers,
 * companies can hand this single file to non-technical reviewers.
 *
 * Usage:
 *   const html = HTMLReportBuilder.build({
 *     project: 'GE9X',
 *     screenshots: { 'engine-overview.png': base64data, ... },
 *     validation: [...],
 *   });
 */

import PartIDRegistry from '../registry/PartIDRegistry.js';
import InteractionRecorder from '../recording/InteractionRecorder.js';

export default class HTMLReportBuilder {

  /**
   * Build the HTML report.
   *
   * @param {object} options
   * @param {string} [options.project='Project']
   * @param {string} [options.subtitle]
   * @param {object} [options.screenshots] - { filename: 'data:image/png;base64,...' or relative path }
   * @param {object[]} [options.validation] - cross-validation checks { name, expected, actual }
   * @param {object[]} [options.specs] - published specifications { label, value }
   * @returns {string} HTML string
   */
  static build(options = {}) {
    const {
      project = 'Project',
      subtitle = '',
      screenshots = {},
      validation = [],
      specs = [],
    } = options;

    const stats = PartIDRegistry.stats();
    const tree = PartIDRegistry.tree();
    const allEntries = PartIDRegistry.all();

    // Aggregate tests + analyses
    const testCounts = { PASS: 0, MARGINAL: 0, FAIL: 0, ERROR: 0, SKIPPED: 0 };
    const analysesCount = allEntries.reduce((s, e) => s + e.analyses.length, 0);
    const allTests = [];
    for (const e of allEntries) {
      for (const t of e.tests) {
        if (testCounts[t.result] !== undefined) testCounts[t.result]++;
        allTests.push({ partID: e.partID, ...t });
      }
    }

    // BOM
    const grouped = new Map();
    for (const e of allEntries) {
      const key = `${e.category}-${e.subsystem}-${e.name}`;
      if (!grouped.has(key)) {
        grouped.set(key, { name: e.name, category: e.category, subsystem: e.subsystem, material: e.material, qty: 0 });
      }
      grouped.get(key).qty++;
    }
    const bom = Array.from(grouped.values()).sort((a, b) => b.qty - a.qty);

    const session = InteractionRecorder.getSession();
    const eventsCount = InteractionRecorder.count();

    // Build the HTML
    const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${HTMLReportBuilder._esc(project)} — ArchDisc Project Report</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>${HTMLReportBuilder._css()}</style>
</head>
<body>
<header>
  <h1>${HTMLReportBuilder._esc(project)}</h1>
  <p class="subtitle">${HTMLReportBuilder._esc(subtitle)}</p>
  <p class="meta">Generated by ArchDisc · ${new Date().toUTCString()}</p>
</header>

<nav>
  <a href="#overview">Overview</a>
  <a href="#screenshots">Screenshots</a>
  <a href="#validation">Validation</a>
  <a href="#categories">Categories</a>
  <a href="#tests">Real-World Tests</a>
  <a href="#bom">BOM</a>
  <a href="#tree">Component Tree</a>
  ${session ? '<a href="#session">Session Log</a>' : ''}
</nav>

<section id="overview">
  <h2>Overview</h2>
  <div class="stats-grid">
    <div class="stat"><div class="num">${stats.total.toLocaleString()}</div><div class="lbl">components</div></div>
    <div class="stat"><div class="num">${Object.keys(stats.byCategory).length}</div><div class="lbl">categories</div></div>
    <div class="stat"><div class="num">${Object.keys(stats.byMaterial).length}</div><div class="lbl">materials</div></div>
    <div class="stat"><div class="num">${stats.totalTests}</div><div class="lbl">tests run</div></div>
    <div class="stat"><div class="num">${analysesCount}</div><div class="lbl">analyses</div></div>
    <div class="stat"><div class="num">${bom.length.toLocaleString()}</div><div class="lbl">BOM entries</div></div>
  </div>
  ${specs.length ? `
  <h3>Published Specifications</h3>
  <table class="spec-table">
    ${specs.map(s => `<tr><td>${HTMLReportBuilder._esc(s.label)}</td><td>${HTMLReportBuilder._esc(s.value)}</td></tr>`).join('')}
  </table>
  ` : ''}
</section>

<section id="screenshots">
  <h2>Visual Renders</h2>
  ${Object.entries(screenshots).length === 0 ? '<p>No screenshots provided.</p>' :
    `<div class="screenshot-grid">${Object.entries(screenshots).map(([name, src]) => `
      <figure>
        <img src="${HTMLReportBuilder._esc(src)}" alt="${HTMLReportBuilder._esc(name)}" loading="lazy">
        <figcaption>${HTMLReportBuilder._esc(name)}</figcaption>
      </figure>
    `).join('')}</div>`
  }
</section>

<section id="validation">
  <h2>Cross-Validation</h2>
  ${validation.length === 0 ? '<p>No validation checks recorded.</p>' :
    `<table class="check-table">
      <thead><tr><th>Check</th><th>Expected</th><th>Actual</th><th>Result</th></tr></thead>
      <tbody>
        ${validation.map(v => {
          const ok = v.actual === v.expected;
          return `<tr class="${ok ? 'pass' : 'fail'}">
            <td>${HTMLReportBuilder._esc(v.name)}</td>
            <td>${HTMLReportBuilder._esc(v.expected)}</td>
            <td>${HTMLReportBuilder._esc(v.actual)}</td>
            <td>${ok ? '<span class="badge pass">PASS</span>' : '<span class="badge fail">FAIL</span>'}</td>
          </tr>`;
        }).join('')}
      </tbody>
    </table>`
  }
</section>

<section id="categories">
  <h2>Components by Category</h2>
  <table class="cat-table">
    <thead><tr><th>Category</th><th>Count</th><th>%</th></tr></thead>
    <tbody>
      ${Object.entries(stats.byCategory).sort((a, b) => b[1] - a[1]).map(([cat, n]) => {
        const pct = (n / stats.total * 100).toFixed(1);
        const barWidth = Math.min(100, n / stats.total * 100 * 5).toFixed(1);
        return `<tr>
          <td><code>${HTMLReportBuilder._esc(cat)}</code></td>
          <td>${n.toLocaleString()}</td>
          <td><span class="bar" style="width: ${barWidth}%">${pct}%</span></td>
        </tr>`;
      }).join('')}
    </tbody>
  </table>

  <h3>Materials</h3>
  <table class="cat-table">
    <thead><tr><th>Material</th><th>Count</th></tr></thead>
    <tbody>
      ${Object.entries(stats.byMaterial).sort((a, b) => b[1] - a[1]).slice(0, 20).map(([mat, n]) =>
        `<tr><td>${HTMLReportBuilder._esc(mat)}</td><td>${n.toLocaleString()}</td></tr>`
      ).join('')}
    </tbody>
  </table>
</section>

<section id="tests">
  <h2>Real-World Test Campaign</h2>
  <div class="stats-grid">
    <div class="stat ok"><div class="num">${testCounts.PASS}</div><div class="lbl">PASS</div></div>
    <div class="stat marginal"><div class="num">${testCounts.MARGINAL}</div><div class="lbl">MARGINAL</div></div>
    <div class="stat fail"><div class="num">${testCounts.FAIL}</div><div class="lbl">FAIL</div></div>
    <div class="stat err"><div class="num">${testCounts.ERROR + testCounts.SKIPPED}</div><div class="lbl">ERR/SKIP</div></div>
  </div>
  ${allTests.length === 0 ? '<p>No tests recorded.</p>' :
    `<details><summary>Show all ${allTests.length} test results</summary>
      <table class="test-table">
        <thead><tr><th>Part ID</th><th>Scenario</th><th>Standard</th><th>Result</th><th>Diagnosis</th></tr></thead>
        <tbody>
          ${allTests.slice(0, 200).map(t => `<tr class="${(t.result || '').toLowerCase()}">
            <td><code>${HTMLReportBuilder._esc(t.partID)}</code></td>
            <td>${HTMLReportBuilder._esc(t.scenario)}</td>
            <td>${HTMLReportBuilder._esc(t.standard || '')}</td>
            <td><span class="badge ${(t.result || '').toLowerCase()}">${HTMLReportBuilder._esc(t.result)}</span></td>
            <td>${HTMLReportBuilder._esc(t.diagnosis || '')}</td>
          </tr>`).join('')}
        </tbody>
      </table>
      ${allTests.length > 200 ? `<p class="muted">… and ${allTests.length - 200} more (truncated)</p>` : ''}
    </details>`
  }
</section>

<section id="bom">
  <h2>Bill of Materials (top 50 by quantity)</h2>
  <table class="bom-table">
    <thead><tr><th>#</th><th>Component</th><th>Category</th><th>Subsystem</th><th>Material</th><th>Qty</th></tr></thead>
    <tbody>
      ${bom.slice(0, 50).map((b, i) => `<tr>
        <td>${i + 1}</td>
        <td>${HTMLReportBuilder._esc(b.name)}</td>
        <td><code>${HTMLReportBuilder._esc(b.category)}</code></td>
        <td><code>${HTMLReportBuilder._esc(b.subsystem)}</code></td>
        <td>${HTMLReportBuilder._esc(b.material)}</td>
        <td class="qty">${b.qty.toLocaleString()}</td>
      </tr>`).join('')}
    </tbody>
  </table>
</section>

<section id="tree">
  <h2>Component Tree</h2>
  <p class="muted">Top-level components shown; full tree is in <code>hierarchy.json</code>.</p>
  <ul class="tree">
    ${tree.slice(0, 100).map(node => HTMLReportBuilder._renderTreeNode(node, 0)).join('')}
  </ul>
</section>

${session ? `<section id="session">
  <h2>Session Log</h2>
  <table class="session-table">
    <tr><td>Session ID</td><td><code>${HTMLReportBuilder._esc(session.sessionID)}</code></td></tr>
    <tr><td>Project</td><td>${HTMLReportBuilder._esc(session.project)}</td></tr>
    <tr><td>User</td><td>${HTMLReportBuilder._esc(session.user)}</td></tr>
    <tr><td>Started</td><td>${HTMLReportBuilder._esc(session.startedAt)}</td></tr>
    <tr><td>Events recorded</td><td>${eventsCount.toLocaleString()}</td></tr>
  </table>
</section>` : ''}

<footer>
  <p>ArchDisc · Proprietary B-Rep Geometry Kernel · v1.21.0</p>
  <p class="muted">29 kernel modules · 13K+ lines · No external CAD dependencies</p>
</footer>

<script>
// Smooth-scroll nav
for (const a of document.querySelectorAll('nav a')) {
  a.addEventListener('click', (e) => {
    const id = a.getAttribute('href').slice(1);
    const target = document.getElementById(id);
    if (target) {
      e.preventDefault();
      target.scrollIntoView({ behavior: 'smooth' });
    }
  });
}
</script>
</body>
</html>`;

    return html;
  }

  static _renderTreeNode(node, depth) {
    const indent = ' style="margin-left:' + (depth * 8) + 'px"';
    const childCount = node.children?.length || 0;
    const summary = `<code>${HTMLReportBuilder._esc(node.id)}</code> · ${HTMLReportBuilder._esc(node.name)} · <span class="muted">${HTMLReportBuilder._esc(node.material)}</span>`;
    if (childCount === 0) {
      return `<li${indent}>${summary}</li>`;
    }
    return `<li${indent}>
      <details>
        <summary>${summary} <span class="muted">[${childCount} children]</span></summary>
        <ul>${node.children.slice(0, 100).map(c => HTMLReportBuilder._renderTreeNode(c, depth + 1)).join('')}</ul>
      </details>
    </li>`;
  }

  static _esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  static _css() {
    return `
* { box-sizing: border-box; }
body {
  font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
  margin: 0; padding: 0;
  background: #0e0e16;
  color: #e6e6ea;
  line-height: 1.5;
}
header {
  background: linear-gradient(135deg, #1a1a2e 0%, #16162a 100%);
  padding: 40px 32px 32px;
  border-bottom: 1px solid #2a2a4e;
}
header h1 { margin: 0; font-size: 36px; color: #fff; }
header .subtitle { color: #8a8aae; margin: 4px 0 0; font-size: 16px; }
header .meta { color: #555570; font-size: 12px; margin-top: 12px; }

nav {
  position: sticky; top: 0;
  background: #16162a;
  padding: 12px 32px;
  border-bottom: 1px solid #2a2a4e;
  z-index: 10;
  display: flex; flex-wrap: wrap; gap: 24px;
}
nav a {
  color: #8aa8d9;
  text-decoration: none;
  font-size: 13px;
  font-weight: 500;
}
nav a:hover { color: #4a90d9; }

section {
  padding: 32px;
  border-bottom: 1px solid #1a1a2e;
}
section h2 { color: #4a90d9; margin: 0 0 16px; font-size: 24px; letter-spacing: 0.5px; }
section h3 { color: #c8c8e0; font-size: 16px; margin: 24px 0 8px; }

.stats-grid {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 12px; margin: 16px 0;
}
.stat {
  background: #16162a;
  border: 1px solid #2a2a4e;
  border-radius: 4px;
  padding: 16px;
  text-align: center;
}
.stat .num { font-size: 28px; font-weight: 700; color: #4a90d9; font-family: 'JetBrains Mono', monospace; }
.stat .lbl { font-size: 11px; color: #8a8aae; text-transform: uppercase; letter-spacing: 0.5px; margin-top: 4px; }
.stat.ok .num { color: #4ed99d; }
.stat.marginal .num { color: #d9c84a; }
.stat.fail .num { color: #d94a90; }
.stat.err .num { color: #999; }

table {
  width: 100%; border-collapse: collapse;
  margin: 12px 0; font-size: 13px;
}
table th, table td {
  text-align: left; padding: 8px 12px;
  border-bottom: 1px solid #1a1a2e;
}
table th { background: #14142a; color: #8aa8d9; font-weight: 500; }
table tr:hover td { background: #14142a; }
table code {
  font-family: 'JetBrains Mono', monospace; font-size: 11px;
  color: #4a90d9;
}
table .qty { text-align: right; font-family: 'JetBrains Mono', monospace; }

.bar {
  display: inline-block;
  background: #4a90d9;
  color: #0e0e16;
  padding: 2px 8px;
  border-radius: 2px;
  font-size: 11px;
  font-family: 'JetBrains Mono', monospace;
  font-weight: 700;
}

.badge {
  display: inline-block; padding: 2px 8px; border-radius: 3px;
  font-size: 10px; font-weight: 700; letter-spacing: 0.5px;
}
.badge.pass { background: #1a3a26; color: #4ed99d; }
.badge.fail { background: #3a1a26; color: #d94a90; }
.badge.marginal { background: #3a3a1a; color: #d9c84a; }
.badge.error { background: #2a2a2a; color: #999; }

.check-table tr.pass td { background: rgba(78, 217, 157, 0.05); }
.check-table tr.fail td { background: rgba(217, 74, 144, 0.05); }
.test-table tr.fail td { background: rgba(217, 74, 144, 0.05); }
.test-table tr.marginal td { background: rgba(217, 200, 74, 0.05); }

.screenshot-grid {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 16px;
}
.screenshot-grid figure {
  margin: 0; background: #14142a;
  border: 1px solid #2a2a4e;
  border-radius: 4px; overflow: hidden;
}
.screenshot-grid img {
  width: 100%; display: block; height: auto;
}
.screenshot-grid figcaption {
  padding: 8px 12px; font-size: 11px; color: #8aa8d9;
  font-family: 'JetBrains Mono', monospace;
  border-top: 1px solid #2a2a4e;
}

.tree { list-style: none; padding-left: 0; font-size: 12px; }
.tree li { padding: 2px 0; }
.tree details summary { cursor: pointer; }
.tree code { font-family: 'JetBrains Mono', monospace; font-size: 10px; color: #4a90d9; }

.muted { color: #8a8aae; font-size: 11px; }

footer {
  padding: 24px 32px; text-align: center;
  background: #08080f; color: #555570; font-size: 11px;
}

details > summary {
  cursor: pointer; padding: 8px 0;
  color: #8aa8d9;
}

@media (max-width: 720px) {
  .screenshot-grid { grid-template-columns: 1fr; }
  nav { gap: 12px; padding: 8px 16px; }
  section { padding: 16px; }
}
`;
  }
}
