/**
 * ArchDisc Foundation — Print Package generator.
 *
 * Bundles a part's STL, drawing, and report into a single self-contained
 * HTML page suitable for handing to a 3D-print farm or fabricator. The
 * page links to the STL file (relative href) and embeds the SVG drawing
 * + a JSON-derived spec table.
 *
 * Also generates an index.html that lists all parts in the package.
 */

function escHtml(s) {
  return String(s).replace(/[&<>"']/g, c => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

/**
 * Build a single-part HTML page.
 *
 * @param {object} part
 * @param {string} part.name
 * @param {string} part.stlFilename     filename of STL relative to this page
 * @param {string} part.svgFilename     filename of drawing relative to this page
 * @param {object} part.report          buildPrintReport output
 * @param {object} part.spec            arbitrary spec table {key: value}
 * @returns {string} HTML
 */
export function buildPartPackageHTML(part) {
  const r = part.report;
  const bb = r.boundingBoxMm;
  const sx = bb.max[0] - bb.min[0];
  const sy = bb.max[1] - bb.min[1];
  const sz = bb.max[2] - bb.min[2];

  const specRows = Object.entries(part.spec || {}).map(([k, v]) =>
    `<tr><td>${escHtml(k)}</td><td>${escHtml(String(v))}</td></tr>`
  ).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${escHtml(part.name)} — ArchDisc Foundation</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif; margin: 0; padding: 24px; color: #1a1a1a; max-width: 1100px; }
  h1 { margin: 0 0 4px; font-size: 22px; font-weight: 700; }
  h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em; color: #666; margin: 24px 0 8px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
  .subtitle { color: #666; font-size: 14px; margin-bottom: 20px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
  .panel { background: #f8f9fa; border: 1px solid #e1e4e8; border-radius: 6px; padding: 14px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid #eee; }
  th { font-weight: 600; color: #555; }
  td:first-child { color: #555; width: 45%; }
  .actions { display: flex; gap: 12px; margin-top: 12px; }
  a.btn { background: #2c5cba; color: white; padding: 8px 14px; border-radius: 4px; text-decoration: none; font-weight: 600; font-size: 13px; }
  a.btn:hover { background: #1f4796; }
  a.btn.secondary { background: #6c757d; }
  a.btn.secondary:hover { background: #545b62; }
  .drawing-frame { background: white; border: 1px solid #ddd; padding: 8px; max-height: 600px; overflow: auto; }
  .drawing-frame iframe { width: 100%; height: 580px; border: none; }
  .small { color: #888; font-size: 12px; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }
  .badge.green { background: #d4edda; color: #155724; }
</style>
</head>
<body>
<h1>${escHtml(part.name)}</h1>
<div class="subtitle">
  Generated by ArchDisc Foundation · ${escHtml(new Date().toISOString().slice(0, 10))} ·
  <span class="badge green">Manifold ✓</span>
</div>

<div class="actions">
  <a class="btn" href="${escHtml(part.stlFilename)}" download>Download STL</a>
  <a class="btn secondary" href="${escHtml(part.svgFilename)}" target="_blank">Open Drawing</a>
  <a class="btn secondary" href="../index.html">Back to Index</a>
</div>

<div class="grid" style="margin-top:24px;">
<div class="panel">
  <h2 style="margin-top:0;">Geometry</h2>
  <table>
    <tr><td>Bounding box</td><td>${sx.toFixed(2)} × ${sy.toFixed(2)} × ${sz.toFixed(2)} mm</td></tr>
    <tr><td>Volume</td><td>${r.volumeMm3.toFixed(1)} mm³</td></tr>
    <tr><td>Surface area</td><td>${r.surfaceAreaMm2.toFixed(1)} mm²</td></tr>
    <tr><td>Triangles</td><td>${r.triangles}</td></tr>
    <tr><td>Vertices</td><td>${r.vertices}</td></tr>
    <tr><td>Edge length range</td><td>${r.edgeLengthRangeMm.min.toFixed(3)} – ${r.edgeLengthRangeMm.max.toFixed(2)} mm</td></tr>
  </table>
</div>

<div class="panel">
  <h2 style="margin-top:0;">Print Notes</h2>
  <table>
    <tr><td>Min wall threshold</td><td>${r.minWallThicknessThresholdMm} mm (FDM-safe)</td></tr>
    <tr><td>Overhang threshold</td><td>${r.overhang.angleThresholdDeg}° from horizontal</td></tr>
    <tr><td>Overhang triangle count</td><td>${r.overhang.triangleCount}</td></tr>
    <tr><td>Overhang area fraction</td><td>${(r.overhang.areaFraction * 100).toFixed(1)} %</td></tr>
    <tr><td>Manifold</td><td><span class="badge green">guaranteed by manifold-3d</span></td></tr>
  </table>
  <div class="small" style="margin-top:8px;">
    Overhang area &gt;30 % typically needs supports. Always preview slice in your slicer of choice (PrusaSlicer / Bambu / Cura / Lychee).
  </div>
</div>
</div>

${specRows ? `
<div class="panel" style="margin-top:20px;">
  <h2 style="margin-top:0;">Specification</h2>
  <table>${specRows}</table>
</div>` : ''}

<h2>Engineering Drawing</h2>
<div class="drawing-frame">
  <iframe src="${escHtml(part.svgFilename)}" title="${escHtml(part.name)} drawing"></iframe>
</div>

<div class="small" style="margin-top:24px;">
  This part was modeled using the ArchDisc Foundation pipeline:
  <code>Sketch2D → CrossSection → manifold-3d feature → STL</code>.
  Geometry is topology-robust (no self-intersections, all edges
  manifold) and STL is watertight.
</div>
</body>
</html>`;
}

/**
 * Build the index page listing every part in a print package set.
 */
export function buildIndexHTML(parts, packageName = 'ArchDisc Foundation Package') {
  const rows = parts.map(p => {
    const r = p.report;
    const bb = r.boundingBoxMm;
    const sx = bb.max[0] - bb.min[0];
    const sy = bb.max[1] - bb.min[1];
    const sz = bb.max[2] - bb.min[2];
    return `<tr>
      <td><a href="parts/${escHtml(p.basename)}.html">${escHtml(p.name)}</a></td>
      <td>${sx.toFixed(1)} × ${sy.toFixed(1)} × ${sz.toFixed(1)} mm</td>
      <td>${r.volumeMm3.toFixed(0)} mm³</td>
      <td>${r.triangles}</td>
      <td><a href="parts/${escHtml(p.basename)}.stl" download>STL</a></td>
      <td><a href="parts/${escHtml(p.basename)}.svg" target="_blank">SVG</a></td>
    </tr>`;
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${escHtml(packageName)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif; margin: 0; padding: 32px; color: #1a1a1a; max-width: 1100px; }
  h1 { margin: 0 0 6px; font-size: 26px; }
  .subtitle { color: #666; font-size: 14px; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; }
  th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #e1e4e8; font-size: 14px; }
  th { background: #f6f8fa; font-weight: 600; }
  a { color: #2c5cba; text-decoration: none; }
  a:hover { text-decoration: underline; }
  .small { color: #888; font-size: 12px; margin-top: 24px; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; background: #d4edda; color: #155724; }
</style>
</head>
<body>
<h1>${escHtml(packageName)}</h1>
<div class="subtitle">
  ${parts.length} parts · all manifold-validated · generated ${escHtml(new Date().toISOString().slice(0, 10))}
  <span class="badge" style="margin-left:8px;">ArchDisc Foundation v1</span>
</div>

<table>
<thead>
  <tr><th>Part</th><th>Bbox</th><th>Volume</th><th>Triangles</th><th>STL</th><th>Drawing</th></tr>
</thead>
<tbody>
${rows}
</tbody>
</table>

<div class="small">
  Each part below was modeled using the ArchDisc Foundation pipeline:
  Sketch2D constraint solver → manifold-3d feature operations →
  watertight STL export. Drawings are derived directly from manifold
  triangulation (silhouette + crease edges) using orthographic projection
  with hidden-line removal.
</div>
</body>
</html>`;
}
