/**
 * ArchDisc Foundation — Topological naming.
 *
 * The "topological naming problem" is real CAD's biggest reason a
 * parametric model breaks: when a parent feature changes, the IDs of
 * faces and edges generated by downstream features become invalid, so
 * fillets, holes, and patterns suddenly reference geometry that no
 * longer exists. Production kernels (Parasolid, ACIS, OpenCascade)
 * each carry their own multi-thousand-line "naming graph" to survive
 * these edits.
 *
 * Foundation's contribution here is more modest but real: every solid
 * we build has a NameTable mapping `manifoldOriginalID → featureName`.
 * Because manifold-3d propagates `runOriginalID` through booleans, we
 * can ALWAYS find which input feature each output triangle came from.
 * That gives us face-level provenance even when the geometry has been
 * cut, unioned, and intersected through many ops.
 *
 * Resolving a name to current geometry:
 *
 *   1. Look up the originalID for the requested feature name.
 *   2. Find all triangles in the current Manifold whose originalID
 *      matches.
 *   3. Group them by coplanar normals → that's the named face.
 *
 * If the parent feature changes (e.g. extrude depth), and we re-build
 * the solid, the faces created by that feature will get NEW originalIDs.
 * The NameTable from the original build is INVALID for the rebuild.
 * The fix is to rebuild with the same NameTable: each feature builder
 * accepts a target name and pins the originalID accordingly. This is
 * exactly the architecture below.
 *
 * MVP scope:
 *   - NamedSolid wraps Manifold + Map<name → originalID>
 *   - Builder helpers: namedCube, namedCylinder, namedExtrude, etc.,
 *     each register the resulting solid under a feature name.
 *   - resolveName(name) returns the set of triangles with that
 *     originalID + average normal of the largest planar group within
 *     them ("the face").
 *   - Because manifold-3d's `Manifold.reserveIDs(N)` reserves a contiguous
 *     range, we keep our own counter and call it for each feature.
 */

import { getManifold } from './manifoldKernel.js';

let _idCursor = 1000000;   // start outside the auto-assigned range

/**
 * Reserve N unique original IDs for upcoming features.
 * Returns the first ID (the rest are id+1, id+2, ...).
 */
async function reserveIds(n = 1) {
  const { Manifold } = await getManifold();
  // manifold-3d's Manifold.reserveIDs(N) reserves and returns the first
  // ID. Fall back to our cursor if API not available.
  if (typeof Manifold.reserveIDs === 'function') {
    return Manifold.reserveIDs(n);
  }
  const id = _idCursor;
  _idCursor += n;
  return id;
}

export class NamedSolid {
  /**
   * @param {Manifold} manifold
   * @param {Map<string, number>} nameTable  - name → originalID
   */
  constructor(manifold, nameTable = new Map()) {
    this.manifold = manifold;
    this.nameTable = nameTable;
  }

  /**
   * Tag this whole solid with a feature name.
   * Wraps in `Manifold.asOriginal()` so it has a fresh originalID.
   */
  async name(featureName) {
    const m = this.manifold.asOriginal();
    const id = m.originalID();
    const next = new Map(this.nameTable);
    next.set(featureName, id);
    return new NamedSolid(m, next);
  }

  /**
   * Combine two NamedSolids into one with the merged name table.
   */
  static merge(...solids) {
    const t = new Map();
    for (const s of solids) for (const [k, v] of s.nameTable) t.set(k, v);
    return t;
  }

  /**
   * Resolve a feature name to its triangles in the current geometry.
   * Returns null if the name is unknown or no matching triangles
   * remain (e.g. the feature was completely cut away).
   */
  resolve(featureName) {
    const targetID = this.nameTable.get(featureName);
    if (targetID === undefined) return null;
    const mesh = this.manifold.getMesh();
    if (!mesh.runOriginalID || !mesh.runIndex) {
      return null;   // mesh has no provenance — can't resolve
    }
    // Each "run" is a contiguous span of triangles sharing one originalID.
    const runs = mesh.runOriginalID;
    const runIndex = mesh.runIndex;
    const matchingTris = [];
    for (let r = 0; r < runs.length; r++) {
      if (runs[r] === targetID) {
        const triStart = runIndex[r] / 3;
        const triEnd = runIndex[r + 1] / 3;
        for (let t = triStart; t < triEnd; t++) matchingTris.push(t);
      }
    }
    if (matchingTris.length === 0) return null;
    return {
      featureName,
      originalID: targetID,
      triangleIndices: matchingTris,
      triangleCount: matchingTris.length,
    };
  }

  /**
   * Diagnostic: list every name in the table along with whether it
   * resolves in the current geometry.
   */
  inspect() {
    const out = [];
    for (const [name, id] of this.nameTable) {
      const res = this.resolve(name);
      out.push({
        name, originalID: id,
        present: res !== null,
        triangleCount: res ? res.triangleCount : 0,
      });
    }
    return out;
  }
}

/**
 * Build a named cube. Returns NamedSolid with `name` registered.
 */
export async function namedCube(name, dims, center = false) {
  const { Manifold } = await getManifold();
  const m = Manifold.cube(dims, center).asOriginal();
  const table = new Map();
  table.set(name, m.originalID());
  return new NamedSolid(m, table);
}

/**
 * Build a named cylinder.
 */
export async function namedCylinder(name, height, radius, segments = 32, center = false) {
  const { Manifold } = await getManifold();
  const m = Manifold.cylinder(height, radius, radius, segments, center).asOriginal();
  const table = new Map();
  table.set(name, m.originalID());
  return new NamedSolid(m, table);
}

/**
 * Boolean union, preserving names from both operands.
 */
export async function namedUnion(a, b) {
  const { Manifold } = await getManifold();
  const m = Manifold.union(a.manifold, b.manifold);
  return new NamedSolid(m, NamedSolid.merge(a, b));
}

/**
 * Boolean difference, preserving names from both operands. Note that a
 * name may stop resolving after a difference (cut away faces).
 */
export async function namedSubtract(a, b) {
  const { Manifold } = await getManifold();
  const m = Manifold.difference(a.manifold, b.manifold);
  return new NamedSolid(m, NamedSolid.merge(a, b));
}

export async function namedIntersect(a, b) {
  const { Manifold } = await getManifold();
  const m = Manifold.intersection(a.manifold, b.manifold);
  return new NamedSolid(m, NamedSolid.merge(a, b));
}

/**
 * Apply a transform; preserves names.
 */
export function namedTranslate(s, vec) {
  return new NamedSolid(s.manifold.translate(vec), new Map(s.nameTable));
}
export function namedRotate(s, angles) {
  return new NamedSolid(s.manifold.rotate(angles), new Map(s.nameTable));
}
