/**
 * ArchDisc Foundation — Vendor RFQ email composer.
 *
 * Drafts a "request for quote" email summarising the design, the
 * cost expectation, and the lead-time ask, then returns:
 *
 *   { subject, body, mailtoUrl }
 *
 * The body is plain text (mail clients are paranoid about HTML
 * from local files); the mailto URL is URL-encoded so any
 * `mailto:` handler will open it pre-populated.
 *
 * Browsers can't attach binary files via mailto, so the body
 * carries an explicit instruction line:
 *   "Please find the ZIP package archdisc-vendor-2026-05-15.zip
 *    attached separately (drag-and-drop into your reply)."
 */

export function buildVendorRFQEmail({ vendorPackage, profile, bodies, partName }) {
  const stamp = new Date().toISOString().slice(0, 10);
  const totals = vendorPackage?.manifest?.totals ?? null;
  const fileNames = vendorPackage?.fileNames ?? [];
  const sizeBytes = vendorPackage?.zipBytes?.length ?? 0;
  const zipName = `archdisc-vendor-${stamp}.zip`;

  const name = partName ?? vendorPackage?.manifest?.partName ?? 'ArchDisc Part';
  const material = vendorPackage?.manifest?.material ?? profile?.materialDefault ?? 'Aluminum 6061-T6';
  const partCount = bodies?.length ?? totals?.partCount ?? 1;

  const subject = `RFQ — ${name} · ${partCount} part${partCount === 1 ? '' : 's'} · ${material}`;

  const lines = [];
  lines.push(`Hello ${profile?.name ?? 'Vendor'} team,`);
  lines.push('');
  lines.push(`Please quote the attached design for production. Summary below; full drawings, G-code (if any), DFM, and cost rollup are in the ZIP attachment.`);
  lines.push('');
  lines.push(`Part name : ${name}`);
  lines.push(`Material  : ${material}`);
  lines.push(`Quantity  : ${partCount} part${partCount === 1 ? '' : 's'} per release`);
  if (totals) {
    lines.push(`Mass      : ${(totals.mass_kg * 1000).toFixed(0)} g (total)`);
    lines.push(`Our cost  : $${totals.totalCost.toFixed(2)} estimated`);
    lines.push(`Sell ref. : $${totals.sellPrice.toFixed(2)} at ${totals.marginPct.toFixed(0)}% margin`);
  }
  if (profile?.leadTimeDays) {
    lines.push(`Lead time : ≤ ${profile.leadTimeDays} days requested`);
  }
  lines.push('');
  lines.push(`Attachment: ${zipName} (${(sizeBytes / 1024).toFixed(1)} KB, ${fileNames.length} files)`);
  lines.push(`Contents  : ${fileNames.slice(0, 6).join(', ')}${fileNames.length > 6 ? ', …' : ''}`);
  lines.push('');
  lines.push(`Please respond with:`);
  lines.push(`  • Confirmation of material availability`);
  lines.push(`  • Unit price + tooling NRE`);
  lines.push(`  • Lead time from PO`);
  lines.push(`  • Inspection certificate level (CofC / FAI / CMM)`);
  lines.push('');
  lines.push(`Generated by ArchDisc on ${new Date().toISOString().slice(0, 10)}.`);
  lines.push(`(Drag-and-drop ${zipName} into your reply — most browsers cannot attach`);
  lines.push(` binary files via mailto:.)`);

  const body = lines.join('\n');
  const mailtoUrl = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;

  return { subject, body, mailtoUrl, zipName };
}
