// ui/test/capability_manifest_test.cpp
//
// THE APP SURFACE, PINNED. What can a user actually invoke?
//
// Archie is required to emit only operations a user can reach in the Forge app. That
// promise is unenforceable while the reachable set exists solely as C++ that has to be
// run to be known. This gate renders the LIVE registry -- the same one the application
// builds -- into a committed manifest, and fails when the two disagree in EITHER
// direction:
//
//   * a command added without recording it  -> Archie is not told a capability exists
//   * a command removed or renamed          -> Archie may emit an op users cannot reach
//   * a featureIrOp changed                 -> the IR mapping silently moved
//
// It is built from the SAME calls ForgeFrame::wirePartCommands() makes, not from a
// hand-listed set. A manifest assembled independently of the app would describe a
// surface nobody ships -- exactly the drift it is supposed to catch.
//
// To regenerate after an intended change:  FORGE_WRITE_APP_SURFACE=1 <this binary>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "forge/ui/CommandRegistry.hpp"
#include "forge/ui/ForgeShell.hpp"
#include "forge/ui/PartCommands.hpp"
#include "ui_test_util.hpp"

using namespace forge::ui;
using forge::uitest::Harness;

namespace {

const char* paramTypeName(ParamType t) {
  switch (t) {
    case ParamType::Number: return "number";
    case ParamType::Text:   return "text";
    case ParamType::Flag:   return "flag";
  }
  return "?";
}
const char* sideEffectName(SideEffectClass s) {
  switch (s) {
    case SideEffectClass::ViewOnly:    return "view";
    case SideEffectClass::Selection:   return "selection";
    case SideEffectClass::Document:    return "document";
    case SideEffectClass::Application: return "application";
  }
  return "?";
}
const char* undoName(UndoContract u) {
  switch (u) {
    case UndoContract::NotUndoable: return "none";
    case UndoContract::SingleStep:  return "single";
    case UndoContract::Transaction: return "transaction";
  }
  return "?";
}
const char* previewName(PreviewPolicy p) {
  switch (p) {
    case PreviewPolicy::None:     return "none";
    case PreviewPolicy::OnDemand: return "ondemand";
    case PreviewPolicy::Live:     return "live";
  }
  return "?";
}

// TSV, one row per command, sorted by id (CommandRegistry::ids() is documented as a
// deterministic sorted listing, so the file is stable across runs and platforms).
std::string render(const CommandRegistry& reg) {
  std::ostringstream o;
  o << "# forge app surface -- the commands a user can invoke.\n";
  o << "# GENERATED by ui/test/capability_manifest_test.cpp from the live registry.\n";
  o << "# Regenerate: FORGE_WRITE_APP_SURFACE=1 <capability_manifest_test binary>\n";
  o << "# id\tcategory\tfeatureIrOp\tsideEffect\tundo\tpreview\tversion\tparams\n";
  for (const std::string& id : reg.ids()) {
    const CommandDescriptor* d = reg.find(id);
    if (d == nullptr) continue;  // ids() and find() disagreeing is caught as a count below
    o << d->id << '\t' << d->category << '\t'
      << (d->featureIrOp.empty() ? "-" : d->featureIrOp) << '\t'
      << sideEffectName(d->sideEffect) << '\t' << undoName(d->undo) << '\t'
      << previewName(d->preview) << '\t' << d->version << '\t';
    if (d->schema.empty()) {
      o << '-';
    } else {
      for (std::size_t i = 0; i < d->schema.size(); ++i) {
        const ParamSpec& p = d->schema[i];
        if (i) o << ',';
        o << p.name << ':' << paramTypeName(p.type) << (p.required ? ":required" : ":optional")
          << (p.hasDefault ? ":hasdefault" : "");
      }
    }
    o << '\n';
  }
  return o.str();
}

std::string readFile(const std::string& path, bool& ok) {
  std::ifstream in(path, std::ios::binary);
  if (!in) { ok = false; return {}; }
  std::ostringstream b; b << in.rdbuf(); ok = true; return b.str();
}

std::vector<std::string> lines(const std::string& s) {
  std::vector<std::string> v; std::string cur;
  for (char c : s) { if (c == '\n') { v.push_back(cur); cur.clear(); } else cur += c; }
  if (!cur.empty()) v.push_back(cur);
  return v;
}

}  // namespace

int main() {
  Harness H("capability_manifest");

  // Exactly what ForgeFrame::wirePartCommands() does. The seeds are the two values a
  // Part command consumes; they do not change the descriptor set, but mirroring the
  // app's construction is the point of the gate.
  ForgeShell shell;
  PartDocument doc;
  UndoStack undo;
  doc.seed(IrValueKind::Profile, "sketch.base", "SKETCH", {IrArg::keyword("XY")});
  doc.seed(IrValueKind::Solid, "body.bracket", "BOX",
           {IrArg::num(80.0), IrArg::num(50.0), IrArg::num(20.0)});
  const std::size_t partAdded = registerPartCommands(shell.registry(), doc, undo);

  const CommandRegistry& reg = shell.registry();
  // ids() and find() must agree, or the manifest silently omits rows.
  std::size_t resolvable = 0;
  for (const std::string& id : reg.ids()) if (reg.find(id) != nullptr) ++resolvable;
  CHECK_EQ_INT(resolvable, reg.size());
  CHECK(partAdded > 0);

  const std::string got = render(reg);

#ifdef FORGE_UI_REPO_ROOT
  const std::string path =
      std::string(FORGE_UI_REPO_ROOT) + "/implementation/sacrosanct/APP_SURFACE_MANIFEST.tsv";

  if (std::getenv("FORGE_WRITE_APP_SURFACE") != nullptr) {
    std::ofstream out(path, std::ios::binary);
    out << got;
    std::printf("  [capability_manifest] WROTE %s (%zu commands)\n", path.c_str(), reg.size());
    return H.finish();
  }

  bool ok = false;
  const std::string want = readFile(path, ok);
  if (!ok) {
    std::printf("  [capability_manifest] manifest MISSING at %s\n", path.c_str());
    std::printf("  Regenerate with FORGE_WRITE_APP_SURFACE=1. A missing manifest is RED:\n");
    std::printf("  a check that could not run is not a check that passed.\n");
    CHECK(false);
    return H.finish();
  }

  const std::vector<std::string> g = lines(got), w = lines(want);
  CHECK_EQ_INT(g.size(), w.size());
  const std::size_t n = g.size() < w.size() ? g.size() : w.size();
  std::size_t shown = 0;
  for (std::size_t i = 0; i < n; ++i) {
    if (g[i] != w[i]) {
      if (shown < 8) {
        std::printf("  [capability_manifest] line %zu differs\n    live:      %s\n    committed: %s\n",
                    i + 1, g[i].c_str(), w[i].c_str());
        ++shown;
      }
      CHECK_EQ_STR(g[i], w[i]);
    }
  }
  for (std::size_t i = n; i < g.size(); ++i)
    std::printf("  [capability_manifest] command present LIVE but not committed: %s\n", g[i].c_str());
  for (std::size_t i = n; i < w.size(); ++i)
    std::printf("  [capability_manifest] command committed but GONE from the app: %s\n", w[i].c_str());
#endif

  return H.finish();
}
