/**
 * ArchDisc — Deliverable Package.
 *
 * Generates the honest build report for an autonomous build: every component,
 * its measured volume, its STEP file size, and — crucially — its TRUE
 * verified/best-effort status from the vision-verify loop. The report does not
 * dress up best-effort geometry as a finished product.
 */

/**
 * Build the honest Markdown build report.
 *
 * @param {Array<{id,name,volume,accepted,stepBytes}>} components
 * @param {object} meta  { product }
 * @returns {string} the BUILD_REPORT.md text
 */
export function buildReportMarkdown(components, meta = {}) {
  const product = meta.product ?? 'Product';
  const total = components.length;
  const verified = components.filter((c) => c.accepted).length;
  const bestEffort = total - verified;

  const lines = [];
  lines.push(`# ${product} — Autonomous Build Report`);
  lines.push('');
  lines.push('Generated by the ArchDisc autonomous atomic-CAD sculptor.');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`- Components attempted: **${total}**`);
  lines.push(`- Passed multi-angle vision verification: **${verified}**`);
  lines.push(`- Best-effort (built but not verified): **${bestEffort}**`);
  lines.push('');
  lines.push('Each component was sculpted from scratch by an LLM sequencing '
    + "ArchDisc's atomic CAD operations (sketch, extrude, cut, revolve, "
    + 'patterns), then checked by a vision LLM from five orbited camera angles.');
  lines.push('');
  lines.push('## Components');
  lines.push('');
  lines.push('| id | name | volume (mm^3) | STEP (bytes) | status |');
  lines.push('|----|------|---------------|--------------|--------|');
  for (const c of components) {
    const status = c.accepted ? 'verified' : 'best-effort (unverified)';
    lines.push(`| ${c.id} | ${c.name} | ${Math.round(c.volume ?? 0)} `
      + `| ${c.stepBytes ?? 0} | ${status} |`);
  }
  lines.push('');
  lines.push('## Not included — and why');
  lines.push('');
  lines.push('This deliverable does **not** contain a "fully assembled watch" '
    + 'STEP file or an assembly video. Composing components that did not pass '
    + 'verification and presenting the result as a finished watch would '
    + 'misrepresent what was achieved. The honest deliverable is the set of '
    + 'component STEP files, each labelled with its true status, plus this '
    + 'report.');
  lines.push('');
  lines.push('## Honest assessment');
  lines.push('');
  lines.push('The autonomous build pipeline works end to end — decompose -> '
    + 'sculpt -> multi-angle vision-verify -> STEP-export -> save. The limiting '
    + 'factor is geometric capability: the current atomic operation set cannot '
    + 'produce convincing watch components (compound-curved case, the mechanical '
    + 'movement), and the vision verifier honestly rejects inadequate geometry '
    + 'rather than rubber-stamping it. Closing that gap needs an exact B-rep '
    + 'kernel and a far richer operation set.');
  lines.push('');
  return lines.join('\n');
}
