// GENERATED BY retrieval/test/negative/README.md's rule: one forbidden line per
// file, each one a thing an implementer must not be able to write. This file is
// EXPECTED TO FAIL TO COMPILE. run_injection_gate.sh fails if it succeeds.
//
// A bare double must never become a plan value. There is no such factory.
#include "forge/retrieval/EvidenceRecord.hpp"
#include "forge/retrieval/PlanValue.hpp"
#include "forge/retrieval/SearxngClient.hpp"

using namespace forge::retrieval;

int main() {
  ProvenancedValue v(10.0);   // no constructor takes a double
  return static_cast<int>(v.value());
}
