// GENERATED BY retrieval/test/negative/README.md's rule: one forbidden line per
// file, each one a thing an implementer must not be able to write. This file is
// EXPECTED TO FAIL TO COMPILE. run_injection_gate.sh fails if it succeeds.
//
// A retrieved span must not be usable as a selector or any text argument.
#include "forge/retrieval/EvidenceRecord.hpp"
#include "forge/retrieval/PlanValue.hpp"
#include "forge/retrieval/SearxngClient.hpp"

using namespace forge::retrieval;

int main() {
  const UntrustedText retrieved("face_top");
  GeometryMutation m(MutationOp::Shell);
  m.withText("selector", retrieved);   // deleted overload
  return 0;
}
