// GENERATED BY retrieval/test/negative/README.md's rule: one forbidden line per
// file, each one a thing an implementer must not be able to write. This file is
// EXPECTED TO FAIL TO COMPILE. run_injection_gate.sh fails if it succeeds.
//
// A retrieved span must not be offerable as an operation name.
#include "forge/retrieval/EvidenceRecord.hpp"
#include "forge/retrieval/PlanValue.hpp"
#include "forge/retrieval/SearxngClient.hpp"

using namespace forge::retrieval;

int main() {
  const UntrustedText retrieved("Scale");
  const auto op = mutationOpFromName(retrieved);   // deleted overload
  return op.has_value() ? 1 : 0;
}
