// GENERATED BY retrieval/test/negative/README.md's rule: one forbidden line per
// file, each one a thing an implementer must not be able to write. This file is
// EXPECTED TO FAIL TO COMPILE. run_injection_gate.sh fails if it succeeds.
//
// Only bind() may produce a BoundCitation.
#include "forge/retrieval/EvidenceRecord.hpp"
#include "forge/retrieval/PlanValue.hpp"
#include "forge/retrieval/SearxngClient.hpp"

using namespace forge::retrieval;

int main() {
  BoundCitation bc;   // private constructor
  return static_cast<int>(bc.value());
}
