// GENERATED BY retrieval/test/negative/README.md's rule: one forbidden line per
// file, each one a thing an implementer must not be able to write. This file is
// EXPECTED TO FAIL TO COMPILE. run_injection_gate.sh fails if it succeeds.
//
// Only grant() may produce an operator approval. Same rule as SendApproval.
#include "forge/retrieval/EvidenceRecord.hpp"
#include "forge/retrieval/PlanValue.hpp"
#include "forge/retrieval/SearxngClient.hpp"

using namespace forge::retrieval;

int main() {
  OperatorCitationApproval a;   // private constructor
  return a.granted() ? 1 : 0;
}
