// GENERATED BY retrieval/test/negative/README.md's rule: one forbidden line per
// file, each one a thing an implementer must not be able to write. This file is
// EXPECTED TO FAIL TO COMPILE. run_injection_gate.sh fails if it succeeds.
//
// A CitedCandidate is not a BoundCitation: the operator step cannot be skipped.
#include "forge/retrieval/EvidenceRecord.hpp"
#include "forge/retrieval/PlanValue.hpp"
#include "forge/retrieval/SearxngClient.hpp"

using namespace forge::retrieval;

int main() {
  CitedCandidate c;
  c.value = 99999.0;
  const ProvenancedValue v = ProvenancedValue::fromCitation(c);   // wrong type
  return static_cast<int>(v.value());
}
