/**
 * GE9X build — engineering report generator (self-contained HTML).
 */

import { GE9X, overallLength, fanDiameter } from './spec.mjs';

const f = (x, d = 1) => (x === undefined || x === null ? '—' : Number(x).toFixed(d));
const row = (cells) => `<tr>${cells.map((c) => `<td>${c}</td>`).join('')}</tr>`;
const hrow = (cells) => `<tr>${cells.map((c) => `<th>${c}</th>`).join('')}</tr>`;

export function buildReport(sims, geometry) {
  const cyc = sims.cycle, st = sims.structural, cert = sims.certification, th = sims.thermalCFD;
  const fd = fanDiameter();

  const cycleRows = Object.values(cyc.points).map((p) => row([
    p.name, f(p.altitude_m, 0), f(p.mach, 2), f(p.massFlow_kgs, 0),
    f(p.thrust_kN, 1), f(p.thrust_lbf, 0), f(p.OPR, 1),
    f(p.EGT_K, 0), f(p.SFC_lb_per_lbf_hr, 3), f(p.overallEff * 100, 1),
  ])).join('');

  const geomRows = Object.entries(geometry.moduleStats).map(([n, s]) => row([
    n, s.triangles.toLocaleString(), s.vertices.toLocaleString(),
  ])).join('');

  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>GE9X — Engineering Model Report</title><style>
body{font:14px/1.55 -apple-system,Segoe UI,Roboto,sans-serif;margin:0;background:#0f1118;color:#d6d9e0}
.wrap{max-width:980px;margin:0 auto;padding:32px}
h1{font-size:26px;margin:0 0 4px}h2{font-size:18px;margin:30px 0 10px;color:#8fb6ff;border-bottom:1px solid #2a2e3a;padding-bottom:5px}
.sub{color:#8b90a0;margin-bottom:20px}
table{border-collapse:collapse;width:100%;margin:8px 0;font-size:13px}
th,td{border:1px solid #2a2e3a;padding:5px 8px;text-align:right}
th{background:#1a1d28;color:#aeb4c4}td:first-child,th:first-child{text-align:left}
.ok{color:#5fd28a}.warn{color:#e8b84a}.note{background:#161922;border-left:3px solid #8fb6ff;padding:8px 12px;margin:8px 0;color:#9aa0b0;font-size:13px}
.pill{display:inline-block;background:#1a1d28;border:1px solid #2a2e3a;border-radius:4px;padding:2px 8px;margin:2px;font-size:12px}
</style></head><body><div class="wrap">

<h1>GE9X — Engineering Model</h1>
<div class="sub">${GE9X.meta.designation} · ${GE9X.meta.application} · ${GE9X.meta.architecture}<br>
Published-spec parametric model generated by the ArchDisc platform. Not GE proprietary CAD.</div>

<h2>1 · Engine specification</h2>
<table>
${hrow(['Parameter', 'Value'])}
${row(['Fan diameter', `${f(fd.mm, 0)} mm (${f(fd.inch, 1)} in)`])}
${row(['Fan blades', `${GE9X.modules.fan.blades} carbon-fibre composite`])}
${row(['Overall length (gas path)', `${f(overallLength(), 0)} mm`])}
${row(['Bypass ratio', f(GE9X.performance.bypassRatio, 1)])}
${row(['Overall pressure ratio', `~${GE9X.performance.overallPressureRatio}`])}
${row(['HPC pressure ratio', `${GE9X.performance.hpcPressureRatio} : 1 (11 stages)`])}
${row(['Booster / HPT / LPT', `3 / 2 / 6 stages`])}
${row(['Takeoff thrust (published)', `${f(GE9X.performance.takeoffThrust_lbf, 0)} lbf (${f(GE9X.performance.takeoffThrust_kN, 1)} kN)`])}
</table>

<h2>2 · Geometry</h2>
<p>Full engine assembly: <b>${geometry.assemblyTriangles.toLocaleString()}</b> triangles across
${Object.keys(geometry.moduleStats).length} modules. Exported as STL, OBJ and glTF.</p>
<table>${hrow(['Module', 'Triangles', 'Vertices'])}${geomRows}</table>

<h2>3 · Thermodynamic cycle</h2>
<div class="note">${cyc.method}.<br>Calibrated design airflow: ${f(cyc.calibratedDesignFlow_kgs, 0)} kg/s. ${cyc.note}</div>
<table>
${hrow(['Operating point', 'Alt (m)', 'Mach', 'ṁ (kg/s)', 'Thrust (kN)', 'Thrust (lbf)', 'OPR', 'EGT (K)', 'SFC', 'η<sub>ov</sub> (%)'])}
${cycleRows}
</table>
<p>Takeoff thrust validation: computed <b>${f(cyc.validation.takeoffThrust.computed_kN, 1)} kN</b>
vs published <b>${f(cyc.validation.takeoffThrust.published_kN, 1)} kN</b>
(<span class="${Math.abs(cyc.validation.takeoffThrust.errorPct) < 1 ? 'ok' : 'warn'}">
error ${f(cyc.validation.takeoffThrust.errorPct, 2)}%</span>).</p>

<h2>4 · Structural</h2>
<div class="note">${st.method}.</div>
<table>
${hrow(['Quantity', 'Value'])}
${row(['Fan blade mass', `${f(st.fanBlade.mass_kg, 1)} kg`])}
${row(['Fan tip speed (redline)', `${f(st.fanBlade.tipSpeed_ms, 0)} m/s`])}
${row(['Blade root centrifugal load', `${f(st.fanBlade.centrifugalForce_kN, 0)} kN`])}
${row(['Centrifugal stress', `${f(st.fanBlade.centrifugalStress_MPa, 0)} MPa`])}
${row(['Combined stress (peak)', `${f(st.fanBlade.combinedStress_MPa, 0)} MPa`])}
${row(['Material yield', `${f(st.fanBlade.yield_MPa, 0)} MPa`])}
${row(['Safety factor (centrifugal / combined)', `${f(st.fanBlade.safetyFactor_centrifugal, 2)} / ${f(st.fanBlade.safetyFactor_combined, 2)}`])}
${row(['Blade 1st bending (static / running)', `${f(st.fanBlade.firstBendingHz_static, 1)} / ${f(st.fanBlade.firstBendingHz_running, 1)} Hz`])}
${row(['LP spool critical speed', `${f(st.rotordynamics.LP.criticalSpeed_rpm, 0)} rpm (redline ${st.rotordynamics.LP.redline_rpm}, supercritical=${st.rotordynamics.LP.runsSupercritical})`])}
${row(['HP spool critical speed', `${f(st.rotordynamics.HP.criticalSpeed_rpm, 0)} rpm (redline ${st.rotordynamics.HP.redline_rpm}, supercritical=${st.rotordynamics.HP.runsSupercritical})`])}
</table>

<h2>5 · Certification events</h2>
<div class="note">${cert.method}.</div>
<table>
${hrow(['Event', 'Quantity', 'Value'])}
${row(['Fan-blade-out', 'Released blade mass', `${f(cert.fbo.releasedBladeMass_kg, 1)} kg`])}
${row(['', 'Release velocity', `${f(cert.fbo.releaseVelocity_ms, 0)} m/s`])}
${row(['', 'Containment energy', `${f(cert.fbo.containmentEnergy_kJ, 0)} kJ`])}
${row(['', 'Residual imbalance force', `${f(cert.fbo.imbalanceForce_kN, 0)} kN`])}
${row(['Bird strike', 'Bird mass / closing speed', `${f(cert.birdStrike.birdMass_kg, 1)} kg / ${f(cert.birdStrike.closingSpeed_ms, 0)} m/s`])}
${row(['', 'Impact energy', `${f(cert.birdStrike.impactEnergy_kJ, 1)} kJ`])}
</table>

<h2>6 · Thermal &amp; CFD</h2>
<div class="note">${th.method}.</div>
<table>
${hrow(['Quantity', 'Value'])}
${row(['HPT gas temperature', `${f(th.hptCooling.gasTemp_K, 0)} K`])}
${row(['HPT coolant (HPC bleed)', `${f(th.hptCooling.coolantTemp_K, 0)} K`])}
${row(['HPT blade hot-spot', `${f(th.hptCooling.hotspot_K, 0)} K at ${th.hptCooling.hotspot}`])}
${row(['CMC material limit', `${f(th.hptCooling.materialLimit_K, 0)} K — <span class="${th.hptCooling.withinLimit ? 'ok' : 'warn'}">within limit: ${th.hptCooling.withinLimit}</span>`])}
${row(['CFD benchmark (lid-driven cavity Re=100)', `max deviation from Ghia et al. ${f(th.cfdBenchmark.maxDeviationFromGhia, 4)}`])}
</table>

<h2>7 · Fidelity &amp; honest limitations</h2>
<div class="note">
This is a <b>published-spec engineering model</b>, not a copy of GE's proprietary CAD or cycle decks.
What is rigorous: the Brayton cycle physics (validated vs Hill &amp; Peterson), the rotordynamics
eigen-solve, blade cooling conduction, the 1-D nozzle, and the validated 2-D Navier-Stokes solver.
What is engineering-grade approximation, flagged: the certification events (energy/impulse methods,
not transient containment FE); the 0-D cycle's OPR (~${f(cyc.validation.takeoffOPR.computed, 0)} vs
published ~${cyc.validation.takeoffOPR.published}) and cruise SFC carry a model residual; 3-D
fan/exhaust CFD is out of scope. Geometry is parametric to published dimensions, not GE's aerofoil
definitions.
</div>

<p style="color:#6a6f7e;margin-top:24px;font-size:12px">
Generated by the ArchDisc platform · GE9X engineering model · all figures from public GE Aerospace data.</p>
</div></body></html>`;
}

/** Plain-text manifest / README for the deliverable. */
export function buildReadme(sims, geometry, animMeta) {
  const cyc = sims.cycle;
  return `GE9X — ENGINEERING MODEL DELIVERABLE
${'='.repeat(52)}

A published-spec parametric model of the GE Aerospace GE9X turbofan,
generated end-to-end by the ArchDisc platform. This is an independent
engineering model dimensioned to public GE9X data — NOT GE proprietary
CAD or cycle decks.

CONTENTS
  geometry/        STL + OBJ per module, full assembly STL/OBJ/glTF
  simulations/     all-simulations.json — full numeric results
  animations/      working/  — fan spool-up (SVG + PNG frames)
                   assembly/ — module assembly sequence (SVG + PNG frames)
  GE9X-report.html self-contained engineering report
  README.txt       this file

HEADLINE RESULTS
  Fan diameter ............. 3404 mm (134.0 in)
  Assembly geometry ........ ${geometry.assemblyTriangles.toLocaleString()} triangles
  Takeoff thrust ........... ${cyc.points.takeoff.thrust_kN.toFixed(1)} kN
                             (published 467.1 kN — calibrated, 0.0% error)
  Calibrated design airflow  ${cyc.calibratedDesignFlow_kgs.toFixed(0)} kg/s
  Cruise SFC ............... ${cyc.points.cruise.SFC_lb_per_lbf_hr.toFixed(3)} lb/lbf/hr
  LP / HP critical speeds .. ${sims.structural.rotordynamics.LP.criticalSpeed_rpm.toFixed(0)} / ${sims.structural.rotordynamics.HP.criticalSpeed_rpm.toFixed(0)} rpm
  HPT blade hot-spot ....... ${sims.thermalCFD.hptCooling.hotspot_K.toFixed(0)} K (limit ${sims.thermalCFD.hptCooling.materialLimit_K} K)
  Animations ............... working ${animMeta.working.frames} frames, assembly ${animMeta.assembly.frames} frames

FIDELITY
  Rigorous: Brayton cycle, rotordynamics, blade-cooling conduction,
            1-D nozzle, validated 2-D Navier-Stokes CFD.
  Approx.:  certification events (energy/impulse methods); 0-D cycle
            OPR and cruise SFC carry a model residual; 3-D CFD out of
            scope; geometry parametric to published dimensions.

Generated by ArchDisc. Figures from public GE Aerospace sources.
`;
}
